language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
sudo: false

cache:
  directories:
    - $HOME/.composer/cache


install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit